### ISSUE TITLE
non-SI units break multigraph pyqt plotting

### ISSUE THREAD

**Issue by dmtvanzanten** [qdev-dk/Qcodes#50]
If you encounter a bug use the following template.
If you have a feature request feel free to freestyle.
### Steps to reproduce
1. 
do1d(qdac.ch03_v, 6, 0, 200, 0.02, lockin.g, dmm.volt)
of which lockin has non-SI units, and dmm does have SI units
2. 
tada

### Expected behaviour
it shouldn't break

### Actual behavior
```
do1d(qdac.ch03_v, 6, 0, 200, 0.02, lockin.g, dmm.volt)
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 206, in handleRequest
    opts = pickle.loads(optStr)
  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 724, in unpickleObjectProxy
    obj = getattr(obj, attr)
AttributeError: 'PlotDataItem' object has no attribute '__getitem__'

===== Local Traceback to request follows: =====
Traceback (most recent call last):

  File "<ipython-input-46-49b5c39c837b>", line 1, in <module>
    do1d(qdac.ch03_v, 6, 0, 200, 0.02, lockin.g, dmm.volt)

  File "c:\users\dmtvanzanten\desktop\qdev-qcodes\qcodes\utils\wrappers.py", line 427, in do1d
    do_plots=do_plots)

  File "c:\users\dmtvanzanten\desktop\qdev-qcodes\qcodes\utils\wrappers.py", line 361, in _do_measurement
    plot, _ = _plot_setup(data, meas_params, startranges=startranges)

  File "c:\users\dmtvanzanten\desktop\qdev-qcodes\qcodes\utils\wrappers.py", line 233, in _plot_setup
    _create_plot(plot, i, i.name, data, counter_two, j, 0)

  File "c:\users\dmtvanzanten\desktop\qdev-qcodes\qcodes\utils\wrappers.py", line 169, in _create_plot
    ax = plot.traces[0]['plot_object']['hist'].axis

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 928, in __getitem__
    return self._getSpecialAttr('__getitem__')(*args)

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 918, in __call__
    return self._handler.callObj(obj=self, args=args, kwds=kwds, **opts)

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 567, in callObj
    return self.send(request='callObj', opts=dict(obj=obj, args=args, kwds=kwds), byteData=byteMsgs, **opts)

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 470, in send
    return req.result()

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 636, in result
    while not self.hasResult():

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 654, in hasResult
    self.result(block=False)

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 647, in result
    self._result = self.proc.getResult(self.reqId)  ## raises NoResultError if result is not available yet

  File "C:\Users\dmtvanzanten\Anaconda3\envs\qcodes\lib\site-packages\pyqtgraph\multiprocess\remoteproxy.py", line 508, in getResult
    raise exc

AttributeError: 'PlotDataItem' object has no attribute '__getitem__'
```

### System
WINDOWS 10
master
6d6407c1093f7c637346cc97707cb61b4e111e78

**Comment by WilliamHPNielsen** [comment]
Solved by #52
